# Generated by Django 4.2.4 on 2023-09-01 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Secret',
            fields=[
                ('secret_phrase', models.CharField(max_length=150, primary_key=True, serialize=False, verbose_name='secret_phrase')),
                ('message', models.TextField(verbose_name='message')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='expiration_date')),
            ],
            options={
                'verbose_name': 'secret',
                'verbose_name_plural': 'secrets',
            },
        ),
    ]
