# Generated by Django 4.2.4 on 2023-09-01 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secret',
            name='expiration_date',
            field=models.CharField(blank=True, null=True, verbose_name='expiration_date'),
        ),
    ]
