# Generated by Django 4.2.4 on 2023-09-01 20:22

from django.db import migrations, models
import secret.models


class Migration(migrations.Migration):

    dependencies = [
        ('secret', '0002_alter_secret_expiration_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secret',
            name='expiration_date',
        ),
        migrations.AddField(
            model_name='secret',
            name='expiration_time',
            field=models.CharField(default='7:0:0', max_length=150, validators=[secret.models.validate_expiration], verbose_name='expiration_time'),
        ),
    ]
