# Generated by Django 4.2.4 on 2023-09-01 23:00

from django.db import migrations, models
import secret.models


class Migration(migrations.Migration):

    dependencies = [
        ('secret', '0003_remove_secret_expiration_date_secret_expiration_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secret',
            name='expiration_time',
            field=models.CharField(default='7:0:0', max_length=9, validators=[secret.models.validate_expiration], verbose_name='expiration_time'),
        ),
    ]
